"""Take ownership of the technical documentation DocTypes in code.

Generated by ./codify, then consolidated: twelve DocTypes built through the desk UI on dev
(``custom = 1``) lived only in that site's database. One patch rather than twelve so
the reload order is guaranteed across the whole cluster — child tables first, then the
parents that embed them. `NATO Codification` and its package table are not among them: the
register keeps the NSN code on the modification instead, so those two are left on dev as
the prototype rows they are, with their custom fields intact.

Data is untouched. Each table is `tab<DocType>` whether `custom` is 0 or 1, and no
fieldname changes, so no column is renamed or dropped. On a site that never had the desk
prototypes — prod today — the loop only reloads the JSON migrate has already applied.

The Custom Field rows are deleted because ./codify folded them into the DocType JSON at
their `insert_after` position; keeping both would leave two descriptions of one field,
free to drift apart. The Client Script is disabled rather than deleted: its body stays
recoverable from the site, while the exported technical_document.js takes over. Leaving it
enabled would bind a second handler to the same form events.
"""

import frappe

MODULE = "Technical Documentation"
MODULE_DIR = "technical_documentation"

TARGETS = [
	("Technical Document Revision Row", "technical_document_revision_row"),
	("Technical Document Modification Row", "technical_document_modification_row"),
	("Technical Document Completeness Row", "technical_document_completeness_row"),
	("Document Requirement Item", "document_requirement_item"),
	("Technical Document Type", "technical_document_type"),
	("Product Type", "product_type"),
	("Product Subtype", "product_subtype"),
	("Document Requirement Template", "document_requirement_template"),
	("Technical Document", "technical_document"),
	("Technical Document Revision", "technical_document_revision"),
	("Technical Document Relation", "technical_document_relation"),
	("Product Modification", "product_modification"),
]

DROP_CUSTOM_FIELDS = [
	"Product Modification-discontinued_date",
	"Product Modification-introduction_date",
	"Product Modification-note",
	"Product Modification-product_subtype",
	"Product Modification-product_type",
	"Technical Document Revision-additional_attachment",
	"Technical Document Revision-approval_date",
	"Technical Document Revision-approved_by",
	"Technical Document Revision-change_basis",
	"Technical Document Revision-change_description",
	"Technical Document Revision-checked_by",
	"Technical Document Revision-comment",
	"Technical Document Revision-creation_date",
	"Technical Document Revision-end_date",
	"Technical Document Revision-pdf_file",
	"Technical Document Revision-prepared_by",
	"Technical Document Revision-signed_scan",
	"Technical Document Revision-word_file",
	"Technical Document-codification_overview_html",
	"Technical Document-completeness_html",
	"Technical Document-completeness_rows",
	"Technical Document-current_revision",
	"Technical Document-current_revision_effective_date",
	"Technical Document-linked_records_section",
	"Technical Document-modification_rows",
	"Technical Document-note",
	"Technical Document-product_subtype",
	"Technical Document-product_type",
	"Technical Document-requirement_template",
	"Technical Document-responsible_department",
	"Technical Document-revision_rows",
	"Technical Document-top_columns_break",
]

DISABLE_CLIENT_SCRIPTS = [
	"Technical Document Completeness",
]


def execute():
	for name in frappe.get_all("Custom Field", filters={"name": ("in", DROP_CUSTOM_FIELDS)}, pluck="name"):
		frappe.delete_doc("Custom Field", name, ignore_permissions=True, force=True)

	for name in DISABLE_CLIENT_SCRIPTS:
		if frappe.db.exists("Client Script", name):
			frappe.db.set_value("Client Script", name, "enabled", 0, update_modified=False)

	for doctype, file_name in TARGETS:
		if frappe.db.exists("DocType", doctype):
			frappe.db.set_value(
				"DocType",
				doctype,
				{"custom": 0, "module": MODULE},
				update_modified=False,
			)

		frappe.reload_doc(MODULE_DIR, "doctype", file_name, force=True)
		frappe.clear_cache(doctype=doctype)

	frappe.db.commit()
